name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache_node_modules
      with:
        path: node_modules
        key: node_modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node_modules-${{ runner.os }}-
          node_modules-
    - uses: actions/cache@v3
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      with:
        path: /usr/local/share/.cache/yarn/v6
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-
          yarn-
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn setup
    - run: yarn test
    - uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info

  release:
    if: github.event_name == 'push' && contains('refs/heads/main,refs/heads/beta,refs/heads/alpha', github.ref)
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node_modules-${{ runner.os }}-
          node_modules-
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: ph-fritsche/action-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
